on:
  workflow_dispatch: {}

jobs:
  updateSearchIndex:
    name: Update search index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: darrenjennings/algolia-docsearch-action@da2ed379c147b356d60dbfec68bdcfacb2791a98
        with:
          algolia_application_id: 'E57FOT37U9'
          algolia_api_key: '${{ secrets.ALGOLIA_DOC_SEARCH_CRAWLER_KEY }}'
          file: algolia.config.js
